In [16]:
import os
import numpy as np
import scipy
import reading 
from feature_extractor import feature_extractor
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import svm, metrics
from sklearn.feature_selection import RFECV
from sklearn.pipeline import Pipeline

Load dei Path, Con il sort giusto per far corrispondere i soggetti

In [17]:
paths_MD= reading.data_path("Diffusion_parameters_maps-20230215T134959Z-001","corrected_MD_image")
paths_masks=reading.data_path("Diffusion_space_segmentations-20230215T134839Z-001","Diffusion_space_segmentations-20230215T134839Z-001")


#print((os.path.basename(paths_masks[0]).split('_')[2]))

paths_MD.sort(key=lambda x: int(os.path.basename(x).split('_')[3]))
paths_masks.sort(key=lambda x: int(os.path.basename(x).split('_')[2]))

Feature extraction

In [18]:
region, mean, std=feature_extractor(paths_MD,paths_masks)

Reshape degli array per fare il Dataframe

In [19]:
mean_t=np.transpose(mean)
std_t=np.transpose(std)

Creo DataFrame per mean and std

In [20]:
df_mean = pd.DataFrame(mean_t[1:,1:177],index=mean[0][1:98],columns=region[1:177])
df_std=pd.DataFrame(std_t[1:,1:177],index=std[0][1:98],columns=region[1:177])

df_mean.head()

Left-Lateral-Ventricle  Left-Inf-Lat-Vent  Left-Cerebellum-White-Matter  \
1.0                0.000078           0.002625                      0.001393   
2.0                0.000093           0.002450                      0.001338   
3.0                0.000135           0.002526                      0.001711   
4.0                0.000144           0.002553                      0.001665   
5.0                0.000142           0.002536                      0.001829   

     Left-Cerebellum-Cortex  Left-Thalamus  Left-Caudate  Left-Putamen  \
1.0                0.000837       0.001063      0.001086      0.001244   
2.0                0.000724       0.000878      0.000953      0.000986   
3.0                0.000716       0.000955      0.001038      0.001291   
4.0                0.000769       0.001031      0.001050      0.001144   
5.0                0.000781       0.001109      0.000991      0.001134   

     Left-Pallidum  3rd-Ventricle  4th-Ventricle  ...  wm-rh-superiorfrontal  \
1.0       0.000855       0.000820       0.002566  ...               0.000842   
2.0       0.000773       0.000768       0.002419  ...               0.000781   
3.0       0.000905       0.000885       0.002576  ...               0.000813   
4.0       0.000818       0.000747       0.003102  ...               0.000830   
5.0       0.000794       0.000748       0.002780  ...               0.000835   

     wm-rh-superiorparietal  wm-rh-superiortemporal  wm-rh-supramarginal  \
1.0                0.000906                0.000964             0.000797   
2.0                0.000774                0.000912             0.000757   
3.0                0.000848                0.000803             0.000822   
4.0                0.000848                0.000819             0.000839   
5.0                0.000823                0.000748             0.000813   

     wm-rh-frontalpole  wm-rh-temporalpole  wm-rh-transversetemporal  \
1.0           0.000786            0.000848                  0.000919   
2.0           0.000752            0.000778                  0.000838   
3.0           0.000763            0.001048                  0.001090   
4.0           0.000820            0.000873                  0.000873   
5.0           0.000765            0.000848                  0.000963   

     wm-rh-insula  Left-UnsegmentedWhiteMatter  Right-UnsegmentedWhiteMatter  
1.0      0.000736                     0.000898                      0.000931  
2.0      0.000749                     0.000785                      0.000865  
3.0      0.000780                     0.000910                      0.000919  
4.0      0.000820                     0.000859                      0.000903  
5.0      0.000766                     0.000861                      0.000891  

[5 rows x 176 columns]

Aggiungo i gruppi

In [21]:
a=pd.DataFrame(pd.read_csv('ADNI_dataset_diffusion.csv'))
a.sort_values(by=["Subject"],inplace=True)
group=a["Group"]
a.head()

Subject  Group Sex   Age
67     4002      0   F  74.0
68     4003      0   F  72.0
28     4009      1   M  90.0
69     4018      0   M  76.0
70     4050      0   M  77.0

SVM: creo i set e splitto

In [22]:
X=df_mean.values
y=group.values

X_tr, X_tst, y_tr, y_tst = train_test_split(X, y, test_size=.1, random_state=6)

Modello SVC classico


In [26]:
clf = svm.SVC(kernel="rbf")
clf.fit(X_tr, y_tr)

y_pred = clf.predict(X_tst)
print(metrics.classification_report(y_tst, y_pred)) 

              precision    recall  f1-score   support

           0       0.83      0.71      0.77         7
           1       0.50      0.67      0.57         3

    accuracy                           0.70        10
   macro avg       0.67      0.69      0.67        10
weighted avg       0.73      0.70      0.71        10



Hyperparams tuning con Grid Search

In [24]:
C_range = np.logspace(-2, 10, 13)
gamma_range = np.logspace(-9, 3, 13)
# defining parameter range 
param_grid = {'C': C_range, 'gamma': gamma_range,
              'kernel': ['rbf'], 
              'class_weight':['balanced', None]}

clf = svm.SVC(kernel="rbf")

grid = GridSearchCV(clf, param_grid, refit = True,n_jobs=-1) 

# fitting the model for grid search 
grid.fit(X_tr, y_tr) 
 
# print best parameter after tuning 
print(grid.best_params_) 

grid_predictions = grid.predict(X_tst) 
print(grid_predictions)
print(y_tst)

# print classification report 
print(metrics.classification_report(y_tst, grid_predictions))

{'C': 10000.0, 'class_weight': 'balanced', 'gamma': 1000.0, 'kernel': 'rbf'}
[0 0 1 1 0 0 0 1 0 1]
[0 0 0 1 0 0 0 1 0 1]
              precision    recall  f1-score   support

           0       1.00      0.86      0.92         7
           1       0.75      1.00      0.86         3

    accuracy                           0.90        10
   macro avg       0.88      0.93      0.89        10
weighted avg       0.93      0.90      0.90        10



In [31]:
#RFE on simple classifier (with different kernel)
rfecv = RFECV(
    estimator=svm.SVC(kernel="linear"),
    step=1,
    cv=5,
    scoring="accuracy",
    min_features_to_select=len(a["Subject"]),
    n_jobs=-1,
)

rfecv.fit(X_tr, y_tr)
 
# print best parameter after tuning 
predictions = rfecv.predict(X_tst) 
print(predictions)
print(y_tst)
   
# print classification report 
print(metrics.classification_report(y_tst, predictions)) 

[1 1 1 1 1 1 1 1 1 1]
[0 0 0 1 0 0 0 1 0 1]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         7
           1       0.30      1.00      0.46         3

    accuracy                           0.30        10
   macro avg       0.15      0.50      0.23        10
weighted avg       0.09      0.30      0.14        10



C:\Users\simol\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\simol\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\simol\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

In [32]:
#RFE on grid classifier (result of GridsearchCV)

rfecv = RFECV(
    estimator=grid.best_estimator_,
    step=1,
    cv=5,
    scoring="accuracy",
    min_features_to_select=len(a["Subject"]),
    n_jobs=-1,
)

rfecv.fit(X_tr, y_tr)
 
# print best parameter after tuning 
predictions = rfecv.predict(X_tst) 
print(predictions)
print(y_tst)
   
# print classification report 
print(metrics.classification_report(y_tst, predictions)) 

ValueError: when `importance_getter=='auto'`, the underlying estimator SVC should have `coef_` or `feature_importances_` attribute. Either pass a fitted estimator to feature selector or call fit before calling transform.